### PR TITLE
1999 c0mrade attacks US Defense Department and NASA

### PR DESCRIPTION
**Pull request by rasorro**
I am Robert Rasor; registered in module CSC3632

### CODE REVIEW

**Comment by charlesmorisset** [comment]
There is already an attack named 1999 NASA in the repo, it was just committed by @AnthnyClment, can you please check about the overlap first?

**Comment by rasorro** [comment]
I saw that but he hasn't written anything in it yet, so I wasn't sure if it was going to be the same attack.

**Comment by charlesmorisset** [comment]
Please check with the author by replying to the commit. The instructions clearly specific to put a placeholder first, to avoid exactly this situation.

**Comment by rasorro** [comment]
I'll see if I have any new information to add to it (and see if I can learn anything new about the attack from it). Thank you!

**Pull request closed without merging**
